{
  "language": "python",
  "os": [
    "linux"
  ],
  "dist": "xenial",
  "jobs": {
    "include": [
      {
        "language": "python",
        "python": "3.7",
        "services": [
          "postgresql"
        ],
        "install": [
          "pip install -r requirements.txt"
        ],
        "before_script": [
          "psql -c 'create database dive_test;' -U postgres"
        ],
        "script": [
          "coverage run --omit */site-packages/* -m unittest discover tests",
          "coverage report"
        ],
        "after_success": [
          "coveralls"
        ]
      },
      {
        "language": "node_js",
        "script": [
          "ls"
        ]
      }
    ]
  }
}