{
  "language": "python",
  "os": [
    "linux"
  ],
  "dist": "xenial",
  "jobs": {
    "include": [
      {
        "language": "python",
        "python": "3.7",
        "install": [
          "pip install -r requirements.txt"
        ],
        "script": [
          "python -m unittest"
        ]
      },
      {
        "language": "node_js",
        "script": [
          "ls"
        ]
      }
    ]
  }
}